version: 2
jobs:
  build:
    machine: true
    working_directory: ~/addons-server
    steps:
      - checkout
      - run: >
          printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n'
          "$CIRCLE_SHA1"
          "$CIRCLE_TAG"
          "$CIRCLE_PROJECT_USERNAME"
          "$CIRCLE_PROJECT_REPONAME"
          "$CIRCLE_BUILD_URL"
          > version.json
      - run: echo "Docker deploy here."
  integration_test:
    machine: true
    environment:
      DISPLAY: :99
      PATH: "home/circleci/project/firefox/firefox:$PATH"
    steps:
      - checkout
      - run: git clone https://github.com/mozilla/addons-frontend.git
      - run:
          name: Creating Artifacts
          command: mkdir /tmp/artifacts
      - run:
          command: |
              curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
              echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install yarn
      - run: ./tests/ui/circleci/install-test-depenencies.sh
      - run:
          name: Run tests
          command: |
                pip install tox
                tox -e ui-tests-1 -- --html=/tmp/artifacts/ui-test.html
      - store_artifacts:
          path: /tmp/artifacts/ui-test.html
          destination: ui-test.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration_test
