version: 2
jobs:
  build:
    working_directory: ~/addons-server
    steps:
      - checkout
      - run: >
          printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n'
          "$CIRCLE_SHA1"
          "$CIRCLE_TAG"
          "$CIRCLE_PROJECT_USERNAME"
          "$CIRCLE_PROJECT_REPONAME"
          "$CIRCLE_BUILD_URL"
          > version.json
      - run: echo "Docker deploy here."
  integration_test:
    steps:
      - checkout
      - run: git clone https://github.com/mozilla/addons-frontend.git
      - run:
          name: Creating Artifacts
          command: mkdir /tmp/artifacts
      - run: tox -e ui-tests-1 -- --html=/tmp/artifacts/ui-test.html
      - store_artifacts:
          path: /tmp/ui-test.html
          destination: ui-test.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration_test
