version: 2
jobs:
  build:
    machine: true
    working_directory: ~/addons-server
    steps:
      - checkout
      - run: >
          printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n'
          "$CIRCLE_SHA1"
          "$CIRCLE_TAG"
          "$CIRCLE_PROJECT_USERNAME"
          "$CIRCLE_PROJECT_REPONAME"
          "$CIRCLE_BUILD_URL"
          > version.json
      - run: echo "Docker deploy here."
  integration_test:
    working_directory: ~/addons-server
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start container, verify it's running and start tests
          command: |
            set -x
            docker-compose up -d
            docker-compose run web make -f Makefile-docker initialize_db

            # Try and wait for the container to get ready
            docker run --network container:addonsserver_web_1 \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8000/

            # Run ui-tests
            ./scripts/ui-test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration_test
